Feat/challenge 03 loops conditionals
Enma1920/JavaScript-foundations_challenge-1 pull request #3
Opened 2023-11-04 15:07 UTC by Enma1920

2023-11-05 18:35 UTC, tictools requested changes
`node_modules` folder should never be pushed to remote repository.

In order to remove it, follow these steps:
* remove `node_modules` folder in your remote repository (branch `feat/challenge_03_loops-conditionals`)
* move to your local repo (same branch) and execute `git pull`
* fix requested changes and push them.

2023-11-05 18:35 UTC, tictools commented on challenge_03_loops_conditionals/README.md
`README.md` should live at project root level.

⚠️ FIX: move file at root level

2023-11-05 18:35 UTC, tictools commented on challenge_03_loops_conditionals/loops-conditionals/.DS_Store
⚠️ FIX: remove file and add `.DS_Store` to `.gitignore`

2023-11-05 18:35 UTC, tictools commented on challenge_03_loops_conditionals/loops-conditionals/conditionals/exercise_00.js
> +if (animal == "cat") {
⚠️ FIX: Change animal to different values to make sure it works in all cases

2023-11-05 18:35 UTC, tictools commented on challenge_03_loops_conditionals/loops-conditionals/conditionals/exercise_01.js
> +function Even_Odd(number) {
Variables are always defined using camelCase convention, they never start by capital letter.

```suggestion
function evenOdd(number) {
```

⚠️ FIX: rename function

2023-11-05 18:35 UTC, tictools commented on challenge_03_loops_conditionals/loops-conditionals/conditionals/exercise_01.js
> +console.log(Even_Odd(42));
Your script's output is this one:

```
42 is even
undefined
5 is odd
undefined
```

Do you know why? 🤔

⚠️ FIX: spot the 🐛 and fix it

2023-11-05 18:35 UTC, tictools commented on challenge_03_loops_conditionals/loops-conditionals/loops/exercise_00.js
> +for (let num = 10; num <= 40; num++) {
Avoid mental mapping and abbr.

```suggestion
for (let number = 10; number <= 40; number++) {
```

⚠️ FIX: apply suggestion

2023-11-05 18:35 UTC, tictools commented on challenge_03_loops_conditionals/loops-conditionals/loops/exercise_01.js
> +for (let i = 0; i <= 10; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

This is alwaysthe output of your script
```
Logged In!
Logged In!
Logged In!
Logged In!
Logged In!
Logged In!
Logged In!
Logged In!
Logged In!
Logged In!
Logged In!
```

have you tested it before pushing? 🤔

⚠️ FIX: spot the 🐛 and fix it

2023-11-05 18:35 UTC, tictools commented on challenge_03_loops_conditionals/loops-conditionals/loops/exercise_02.js
> +for (let i = 1; i <= 100; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 18:35 UTC, tictools commented on challenge_03_loops_conditionals/loops-conditionals/while/exercise_00.js
> +let i = 0;
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 18:35 UTC, tictools commented on challenge_03_loops_conditionals/loops-conditionals/while/exercise_02.js
> +let i = 1;
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-12 15:33 UTC, Manel0712 approved these changes
Well Done!

2023-11-12 18:46 UTC, tictools approved these changes

2023-11-12 18:51 UTC, merged